Added an option to hide the list of windows
Airblader/i3 pull request #189
Opened 2018-01-14 19:39 UTC by cylgom

Hi,
This fixes #188 I hope it's clean enough :)

2018-01-15 19:34 UTC, Airblader requested changes
Thanks for your PR!

IMHO the implementation is currently not correct and there's also other minor things. On top of that, please also adapt the `README.md` to mention this feature in the appropriate spot.

Let me know when you pushed the changes so I can review again. Thanks!

2018-01-15 19:34 UTC, Airblader commented on include/config_directives.h
> +CFGFUN(hide_combined_titles, const char *enable);
I don't like this name too much. Can we change it to `force_tabbed_stacked_titlebar yes|no` with `yes` being the default?

2018-01-15 19:34 UTC, Airblader commented on include/configuration.h
> +    /* Disable list of windows in stacked or tabbed mode */
It's not so much a »list of windows«. It's the titlebar of the tabbed or stacked container.

2018-01-15 19:34 UTC, Airblader commented on src/render.c
> +    if (config.hide_combined_titles)
This is not the correct place to decide this. This option should only affect tabbed / stacked containers *and* only if their border is set to anything other than `normal` (i.e., either `pixel` or `none`). So I think the logic has to go into `con_render_tabbed` and similar.

Also, I think `con_border_style` has to be adapted as well. Once all of that is done please test this with various border settings and window layouts (nested tabbed containers, floating etc.) and different configs (enabled window borders etc.).

2018-01-26 10:43 UTC, cylgom commented
I made the changes you requested and it seems to work fine in all cases. Should I pull to have the CI build passed ?

2018-01-26 12:49 UTC, Airblader commented
> I made the changes you requested and it seems to work fine in all cases.

I don't see you ever setting the default value to `true`, so I assume that the option is enabled by default currently (which we don't want). Also, please add a section to the README explaining the feature. :-)

> Should I pull to have the CI build passed ?

Rebasing (not merging) the current gaps-next branch would be great, yes :-)

2018-01-28 13:33 UTC, cylgom commented
All done ! I noticed the smart gaps option does not have a default value in config.c btw, I'm curious: is there a specific reason to this ?

2018-01-28 14:27 UTC, Airblader commented on src/render.c
> +        child->deco_rect.height = (child->border_style == BS_PIXEL ? 1 : 0);
Where does this `1` come from? Actually, this makes me think… shouldn't the descendants of stacked / tabbed containers also get the border on the top if `force_tabbed_stacked_titlebar` is disabled?

2018-01-28 14:27 UTC, Airblader commented
> I noticed the smart gaps option does not have a default value in config.c btw, I'm curious: is there a specific reason to this?

The default of a boolean is false, respectively the default of an enum is 0. So if that's the intended default, it doesn't have to be set explicitly. Since we use a command here which has true as the default, we need to set it explicitly.

I'd like to change the README message, but I can do that after merging this. I do also have a couple more questions, see comment. Lastly, before we merge this we'll need to squash the commits, so you can do that already as well. Thanks!

2018-03-21 07:48 UTC, Airblader commented
Hi, are you going to continue working on this?

2018-03-21 11:46 UTC, cylgom commented
Wow I forgot this I guess... I'll give it a try this afternoon and let you know if I can't get it to work properly. Thank you for your patience!

2018-03-21 17:56 UTC, cylgom commented
I fixed the top border not appearing and squashed+rebased, however I don't remember where that '1' in render.c came from...

2018-03-24 17:58 UTC, Airblader commented
I think the `1` is wrong because it only accounts for `pixel 1` borders, not for `pixel 10` etc. And I also think to correctly show the top border for stacked / tabbed containers we'd probably need to make changes to things like `con_get_border_style_rect`, possibly other places as well. I haven't investigated this in detail, though.

2019-08-28 03:56 UTC, ifohancroft commented
Are there any news on this? As in is it getting merged or did it get merged already? Does it work with the current version?

2019-08-28 04:19 UTC, Airblader commented
You can see the status right here: it's still open and there are comments that haven't been addressed.

2019-08-28 04:21 UTC, ifohancroft commented
You are right. Sorry, I missed that.

2019-10-28 16:12 UTC, Yohannfra commented
Hi, are there any news on this ? Are you still working on it ?

2019-11-24 09:26 UTC, closed without merging