Converting outer gaps into side-specific gaps, also allowing outer/horizontal/vertical
Airblader/i3 pull request #211
Opened 2018-04-29 01:43 UTC by cameronleger

Commit Notes:
```
Using e2f1093 as a reference
Outer gaps split into top, right, bottom, and left
Outer, horizontal, and vertical options added to control all/some sides
README updates for new configuration options
```

This is an alternative to #210 based on user feedback. It has a number of important differences that I want to layout for discussion.

The previous PR added horizontal and vertical gaps. This PR replaces outer gaps with top, right, bottom, and left gaps while providing syntatical sugar for modifying outer, horizontal, and vertical gaps. While the commands and config settings are extremely similar to the current version, the backend is different and I bet that will break some backwards compatibility. I do not know enough to imagine the possibilities, but later I will touch on i3ipc's impacts. Similar to how one should apply workspace-specific gaps after applying global gaps, now one must apply higher-level gaps before side-specific gaps. Otherwise, 'setting' an outer gap would replace the side-specific values.

For the example README config, I slightly tweaked it and made the return key go back into the top gaps mode because I found that when modifying anything other than inner/outer, you're probably adjusting a few things.

Most changes are similar to previous commits and are probably easy to compare and understand. However, I refactored config_directives.c in a different way than before. Instead of passing a single value, it passes a gaps_t struct with only the relevant members modified, and it only applies updates to the relevant members based on the scope. Also, it is overall more verbose, however there is less computations on strings and it exits earlier when possible.

Back to i3ipc.c; originally I was swapping the outer node with the new top/right/bottom/left ints. However, I noted that this broke compatibility with the Python i3ipc package since it has minimal support for gaps, but it expects inner and outer in the JSON. I don't know how many programs this would affect, but I have created my own extensive workspace manager based on this package and it couldn't start because of the i3ipc module failing. So, I've left an outer definition in the JSON, but it only contains the 'top' value. At least i3ipc will continue to work, but anything relying on modifying gaps will probably not function correctly. I'm up for suggestions on managing this; perhaps making 'outer' a map that contains all side values will work, but that might also break outdated programs.

Finally, re: #22, I applied and updated the potential fix located [here](https://github.com/op8867555/i3-gaps/commit/26bdec7a80a05644e2c020c09951c837013182a5), however I don't think it was working correctly so I have not included it here. It definitely solved the fact that only edge containers are modified by outer gaps, but it introduced more issues for the right and bottom sides. When I 'set' them to 0, they extended much further past the screen than the edge, and I had to 'minus' them back to normal. I'm not too versed on the relevant math in render.c to know what to tweak, but I can look into this more. I believe this issue will be more pronounce with this PR; for example add three windows on a workspace, only adjust the left or right gaps, and notice that only the left-most or right-most containers will adjust.

2018-09-29 02:45 UTC, dt-rush commented
I tried to build `cameronleger:feature-54-all` just now and `autoreconf` fails with:

```
configure.ac:120: error: required file './ar-lib' not found
configure.ac:120:   'automake --add-missing' can install 'ar-lib'
configure.ac:60: error: required file './compile' not found
configure.ac:60:   'automake --add-missing' can install 'compile'
configure.ac:7: error: required file './config.guess' not found
configure.ac:7:   'automake --add-missing' can install 'config.guess'
configure.ac:7: error: required file './config.sub' not found
configure.ac:7:   'automake --add-missing' can install 'config.sub'
configure.ac:8: error: required file './install-sh' not found
configure.ac:8:   'automake --add-missing' can install 'install-sh'
configure.ac:8: error: required file './missing' not found
configure.ac:8:   'automake --add-missing' can install 'missing'
Makefile.am:229: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: error: required file './depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
parallel-tests: error: required file './test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
autoreconf: automake failed with exit status: 1
```

2018-11-03 20:10 UTC, Airblader commented
@cameronleger Hey, thanks for the PR and sorry for the drastically long delay. At quick glance this looks all really good. We'll be releasing i3 4.16 in the next few days and afterwards I think might be a good time to give this PR a chance. If you're still interested, could you update the PR to resolve the merge conflicts? I'd appreciate it!

2018-11-03 20:11 UTC, cameronleger commented
On it :) FWIW, I've been running this without issues ever since I made it.

2018-11-03 20:11 UTC, Airblader commented
Oh and if you do, please also make sure to properly rebase the PR onto gaps-next (instead of merging it in) and squashing the commits down so we can have a clean (and potentially revertable) commit history. Thank you!

2018-11-03 20:12 UTC, Airblader commented
Awesome, I'm happy to hear that we already have (quite some) time with someone running it.

2018-11-03 20:17 UTC, Airblader requested changes
Also just a couple of very minor things that would be great if you could take care of them. Here as well please make sure to squash them so we have a single commit for this.

2018-11-03 20:17 UTC, Airblader commented on src/commands.c
> +        if (!strcmp(type, "top") || !strcmp(type, "vertical") || !strcmp(type, "outer")) {
I think we can just use `else if`s here and remove the `invalid` flag again, right?

2018-11-03 20:17 UTC, Airblader commented on src/con.c
> +bool has_outer_gaps(gaps_t gaps) {
Please make this function `static`, otherwise Travis will complain with the warnings enabled there.

2018-11-03 20:17 UTC, Airblader commented on src/config_directives.c
> +            if (!strcmp(scope, "inner"))
I know this wasn't from you, originally, but could we please also add `{}` here?

2018-11-03 20:17 UTC, Airblader commented on src/config_directives.c
> +            else if (!strcmp(scope, "right"))
Here and following, please also use `{}`. Also further down in the changes of `create_gaps_assignment`.

2018-11-03 20:22 UTC, Airblader commented
@SirCmpwn FYI, if we merge this I don't know if you'd want a change to add compat for it in sway.

2018-11-03 20:22 UTC, ddevault commented
Thanks, I'll add a ticket.

2018-11-03 20:28 UTC, cameronleger commented
@Airblader, one more thing to consider: the https://github.com/acrisci/i3ipc-python module completely breaks when this branch is used. I assume the same is true of https://github.com/acrisci/i3ipc-python.

I made a Python app to manage my workspaces, so I have already made the required changes to that module in a local repository for it to continue working with this change.

2018-11-03 20:30 UTC, Airblader commented
Can you specify "completely breaks"? The old syntax still works, the only breaking change I could think of is when using the new feature, the inner/outer properties on the IPC responses will no longer be correct, right? That'd mean that users not using these new features shouldn't have issues. Or am I mistaken?

2018-11-03 20:37 UTC, cameronleger commented
OK please ignore that, I must have been mistaken as I just pulled the latest code there, installed it, and it still works.

I definitely remember modifying it, but perhaps it was with the other branch that we're not going with.

2018-11-04 14:48 UTC, Airblader commented
4.16 is released now, so we can go ahead with this once the changes are done. Just a minor note, I will be travelling for the next few days, so I'm not 100% sure I have time to merge it during that time, but I'll be back by the end of the week.

2018-11-05 10:44 UTC, Airblader commented
Superseded by #249

Note: You can force-push onto an existing PR to update it, no need to open new ones. ;-)

2018-11-05 10:44 UTC, closed without merging

2018-11-06 21:17 UTC, pkieltyka commented
nicely done! would be awesome to have another release with this feature so pkg managers can pick it up

2018-11-06 21:33 UTC, Airblader commented
The releases of i3-gaps are aligned with i3. I specifically waited for the 4.16 release so that this change will have a period of testing before being included in a release. On Arch-based systems you can find i3-gaps-next-git in the AUR.

2018-11-06 21:45 UTC, pkieltyka commented
@Airblader got it, that makes sense. I've reinstalled i3-gaps-next-git and now have the new feature. works like a charm! thanks